version: '3'
services:
  app:
    build:
      context: ./node
      dockerfile: Dockerfile
    networks:
      - rede-ngnix-node

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - '80:80'
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - rede-ngnix-node

networks:
  rede-ngnix-node:
    external: true